version: "3.9"
services:

  postgres:
    image: postgres:14.1-alpine3.15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=immoblock

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/immoblock?sslmode=disable
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    entrypoint:
      [
        "/bin/sh",
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/bin/sh",
        "/app/wait-for.sh",
        "redis:6379",
        "--",
        "/bin/sh",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
